# setup
setup: scan

# Loss
criterion: scan
criterion_kwargs:
   entropy_weight: 5.0

# Model
backbone: resnet50
num_heads: 10 # Use multiple heads

# Dataset
train_db_name: imagenet
val_db_name: imagenet
num_classes: 1000
num_neighbors: 50

transformation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

num_workers: 8
batch_size: 256
