# setup
setup: scan

# Loss
criterion: scan
criterion_kwargs:
   entropy_weight: 5.0

# Model
backbone: resnet50

# Weight update
update_cluster_head_only: False # Train only linear layer during SCAN
num_heads: 1 # Use multiple heads

# Dataset
train_db_name: imagenet_50-2
val_db_name: imagenet_50-2
num_classes: 50
num_neighbors: 20 

# Transformations
augmentation_strategy: ours 
augmentation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 32
     random: True

transformation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
epochs: 100
batch_size: 512
num_workers: 8

# Scheduler
scheduler: constant
