# setup
setup: scan

# Loss
criterion: scan
criterion_kwargs:
   entropy_weight: 5.0

# Weight update
update_cluster_head_only: False # Update full network in SCAN
num_heads: 1

# Model
backbone: resnet50

# Dataset
train_db_name: imagenet
val_db_name: imagenet
num_classes: 1000
num_neighbors: 20

# Transformations
augmentation_strategy: ours 
augmentation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 16
     random: True

transformation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Hyperparameters
#optimizer: sgd
#optimizer_kwargs:
#   lr: 30.0
#   weight_decay: 0.0000
#   nesterov: False
#   momentum: 0.9
#epochs: 100
#batch_size: 512
#num_workers: 16

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.001
   weight_decay: 0.0001
epochs: 100
batch_size: 512
num_workers: 8

# Scheduler
#scheduler: constant

scheduler: cosine
scheduler_kwargs:
   lr_decay_rate: 0.1
