# Setup
setup: simclr

pretrain_path: /vulcanscratch/mgwillia/unsupervised-classification/backbones/btwins_r50_1000.pth.tar

# Model
backbone: resnet50
model_kwargs:
   head: mlp
   features_dim: 128

# Dataset
train_db_name: cub
val_db_name: cub
num_classes: 200
temperature: 0.07
num_neighbors: 10

batch_size: 64 
num_workers: 8

transformation_kwargs:
   resize: 256
   crop_size: 224 
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
