# Setup
setup: simclr

pretrain_path: /vulcanscratch/mgwillia/unsupervised-classification/cifar-10/pretext/model.pth.tar

# Model
backbone: resnet50
model_kwargs:
   head: mlp
   features_dim: 128

# Dataset
train_db_name: cifar-10
val_db_name: cifar-10
num_classes: 10
temperature: 0.07
num_neighbors: 20

batch_size: 512 
num_workers: 8

transformation_kwargs:
   crop_size: 32
   normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]
