# Setup
setup: moco # MoCo is used here

pretrain_path: /vulcanscratch/mgwillia/unsupervised-classification/backbones/moco_r50_200.pth.tar

# Model
backbone: resnet50
model_kwargs:
   head: mlp
   features_dim: 128

# Dataset
train_db_name: imagenet
val_db_name: imagenet
num_classes: 1000
temperature: 0.07
num_neighbors: 20

# Batch size and workers
batch_size: 256 
num_workers: 8

# Transformations
transformation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
