# setup
setup: linearprobe

# Loss
criterion: linearprobe

update_cluster_head_only: True

# Model
backbone: resnet50

# Dataset
train_db_name: imagenet_200-d
val_db_name: imagenet_200-d
num_classes: 50

# Transformations
augmentation_strategy: standard 
augmentation_kwargs:
   random_resized_crop:
      size: 224
      scale: [0.5, 1.0]
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

transformation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.001
   weight_decay: 0.000001
epochs: 100
batch_size: 512
num_workers: 16

# Scheduler
scheduler: constant
