# setup
setup: linearprobe

# Loss
criterion: linearprobe

backbone_path: /vulcanscratch/mgwillia/unsupervised-classification/imagenet/pretext/model.pth.tar

update_cluster_head_only: True

# Model
backbone: resnet50

# Dataset
train_db_name: imagenet
val_db_name: imagenet
num_classes: 1000

# Transformations
augmentation_strategy: standard 
augmentation_kwargs:
   random_resized_crop:
      size: 224
      scale: [0.5, 1.0]
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

transformation_kwargs:
   crop_size: 32
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.001
   weight_decay: 0.0001
epochs: 50
batch_size: 512
num_workers: 16

# Scheduler
scheduler: constant
